#!/bin/bash

# This is executed by the lifecycle postStart so the environment
# will include PATH and such. systemd services in container-httpd
# only use the HTTPD_ ones defined.
#
env | grep "^HTTPD_" | sort > /etc/container-environment
